const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=2)=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:d});
const now=()=>new Date().toISOString();
const DEFAULTS={
  settings:{capital:400000000,riskPct:1,currency:'TOMAN',dgGoldPrice:0},
  symbols:[
    {venue:'Toobit',symbol:'BTCUSDT',label:'BTC / USDT'},
    {venue:'Toobit',symbol:'ETHUSDT',label:'ETH / USDT'},
    {venue:'Toobit',symbol:'SOLUSDT',label:'SOL / USDT'},
    {venue:'Nobitex',symbol:'USDTIRT',label:'USDT / IRT'},
    {venue:'Nobitex',symbol:'BTCIRT',label:'BTC / IRT'},
    {venue:'Nobitex',symbol:'ETHIRT',label:'ETH / IRT'},
    {venue:'Digikala Gold',symbol:'GOLD18',label:'Digital Gold'}
  ], journal:[]
};
function load(){let x;try{x=JSON.parse(localStorage.getItem('tajdara_mm')||'null')}catch{};return Object.assign(structuredClone(DEFAULTS),x||{});}
let state=load(), prices={}, tab='dashboard';
function save(){localStorage.setItem('tajdara_mm',JSON.stringify(state));}
function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function modal(html){$('#modalCard').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});

async function toobitTicker(symbol){let r=await fetch(`https://api.toobit.com/quote/v1/ticker/24hr?symbol=${encodeURIComponent(symbol)}`);let d=await r.json();if(Array.isArray(d))d=d[0];return {price:+(d.c||d.lastPrice||d.p||0),change:+(d.pcp||d.priceChangePercent||0)};}
async function nobitexTicker(symbol){let r=await fetch(`https://apiv2.nobitex.ir/v3/orderbook/${encodeURIComponent(symbol)}`);let d=await r.json();let f=symbol.endsWith('IRT')?10:1;return {price:+d.lastTradePrice/f,change:0};}
async function refreshPrices(){
  let tasks=state.symbols.map(async s=>{try{if(s.venue==='Toobit')prices[s.symbol]=await toobitTicker(s.symbol);else if(s.venue==='Nobitex')prices[s.symbol]=await nobitexTicker(s.symbol);else prices[s.symbol]={price:+state.settings.dgGoldPrice||0,change:0};}catch(e){prices[s.symbol]=prices[s.symbol]||{price:0,change:0,error:true}}});
  await Promise.all(tasks); render(); toast('Market data refreshed');
}

function nav(){ $$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); }
function render(){nav();({dashboard:renderDashboard,markets:renderMarkets,planner:renderPlanner,journal:renderJournal,settings:renderSettings}[tab])();}

function realizedPL(t){let buys=(t.fills||[]).filter(f=>f.type==='BUY'), sells=(t.fills||[]).filter(f=>f.type==='SELL');let bq=buys.reduce((a,x)=>a+x.qty,0), bc=buys.reduce((a,x)=>a+x.qty*x.price+(x.fee||0),0), sq=sells.reduce((a,x)=>a+x.qty,0), sv=sells.reduce((a,x)=>a+x.qty*x.price-(x.fee||0),0);let avg=bq?bc/bq:0;return {bq,sq,avg,pl:sv-sq*avg,open:Math.max(0,bq-sq)};}
function renderDashboard(){let realized=state.journal.reduce((a,t)=>a+realizedPL(t).pl,0), open=state.journal.filter(t=>realizedPL(t).open>0).length;
$('#view').innerHTML=`<div class="grid two">
<div class="card"><div class="label">Trading Capital</div><div class="metric">${fmt(state.settings.capital,0)}</div><div class="subtle">TOMAN</div></div>
<div class="card"><div class="label">Realized P/L</div><div class="metric small ${realized>=0?'pos':'neg'}">${fmt(realized,0)}</div><div class="subtle">TOMAN</div></div>
<div class="card"><div class="label">Open Trades</div><div class="metric">${open}</div></div>
<div class="card"><div class="label">Risk / Trade</div><div class="metric">${fmt(state.settings.riskPct,1)}%</div></div>
</div>
<div class="section-title"><h2>Watchlist</h2><button onclick="refreshPrices()">Refresh</button></div>
<div class="card">${state.symbols.slice(0,6).map(marketRow).join('')}</div>
<div class="section-title"><h2>Mobile Workflow</h2></div><div class="card"><div class="subtle">Scan market → build plan → size position → record fills → edit journal → review realized P/L. No automatic order execution.</div></div>`}
function marketRow(s){let p=prices[s.symbol]||{}, val=p.price?fmt(p.price,p.price<100?4:0):'—';return `<div class="market-row" onclick="openMarket('${s.venue}','${s.symbol}')"><div><div class="symbol">${s.label}</div><div class="venue">${s.venue}</div></div><div><div class="price">${val}</div><div class="chg ${p.change>=0?'pos':'neg'}">${p.change?fmt(p.change,2)+'%':' '}</div></div></div>`}

function renderMarkets(){$('#view').innerHTML=`<div class="section-title"><h2>Markets</h2><button onclick="addSymbolModal()">+ Symbol</button></div><div class="card">${state.symbols.map(s=>marketRow(s)+`<div class="row" style="margin:-6px 0 8px"><div class="spacer"></div><button class="btn secondary" onclick="event.stopPropagation();removeSymbol('${s.venue}','${s.symbol}')">Remove</button></div>`).join('')}</div>`}
function addSymbolModal(){modal(`<h2>Add Market</h2><div class="form-grid"><div class="field full"><label>Venue</label><select id="mVenue"><option>Toobit</option><option>Nobitex</option><option>Digikala Gold</option></select></div><div class="field full"><label>Symbol</label><input id="mSymbol" placeholder="e.g. XRPUSDT or DOGEIRT"></div><div class="field full"><label>Display Name</label><input id="mLabel" placeholder="e.g. XRP / USDT"></div></div><div class="hr"></div><button class="btn block" onclick="addSymbol()">Add Market</button>`)}
function addSymbol(){let venue=$('#mVenue').value,symbol=$('#mSymbol').value.trim().toUpperCase(),label=$('#mLabel').value.trim()||symbol;if(!symbol)return;state.symbols.push({venue,symbol,label});save();closeModal();render();refreshPrices()}
function removeSymbol(v,s){state.symbols=state.symbols.filter(x=>!(x.venue===v&&x.symbol===s));save();render()}

async function openMarket(v,s){let sym=state.symbols.find(x=>x.venue===v&&x.symbol===s),p=prices[s]||{};modal(`<h2>${sym?.label||s}</h2><div class="row"><span class="pill">${v}</span><div class="spacer"></div><strong>${p.price?fmt(p.price,p.price<100?4:0):'—'}</strong></div><div class="hr"></div><canvas id="chart" width="700" height="360"></canvas><div class="subtle" style="margin-top:10px">Chart uses public market candles when available. Smart Money labels are heuristic, not guarantees.</div><div class="hr"></div><button class="btn block" onclick="prefillPlanner('${v}','${s}')">Create Trade Plan</button>`);drawMarket(v,s)}
async function candles(v,s){try{if(v==='Toobit'){let r=await fetch(`https://api.toobit.com/quote/v1/klines?symbol=${s}&interval=1h&limit=90`),d=await r.json();return d.map(x=>({o:+x[1],h:+x[2],l:+x[3],c:+x[4]}));}if(v==='Nobitex'){let to=Math.floor(Date.now()/1000),from=to-90*3600;let r=await fetch(`https://apiv2.nobitex.ir/market/udf/history?symbol=${s}&resolution=60&from=${from}&to=${to}`),d=await r.json(),f=s.endsWith('IRT')?10:1;return (d.t||[]).map((_,i)=>({o:+d.o[i]/f,h:+d.h[i]/f,l:+d.l[i]/f,c:+d.c[i]/f}));}}catch{}return[]}
async function drawMarket(v,s){let c=$('#chart');if(!c)return;let ctx=c.getContext('2d'),rows=await candles(v,s);ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#101813';ctx.fillRect(0,0,c.width,c.height);if(!rows.length){ctx.fillStyle='#9eafa5';ctx.font='22px sans-serif';ctx.fillText('Chart unavailable. Use live quote / manual plan.',30,70);return;}let lo=Math.min(...rows.map(x=>x.l)),hi=Math.max(...rows.map(x=>x.h)),pad=30,w=(c.width-pad*2)/rows.length;let y=p=>pad+(hi-p)/(hi-lo)*(c.height-pad*2);ctx.strokeStyle='#2d4035';for(let i=0;i<5;i++){let yy=pad+i*(c.height-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(c.width-pad,yy);ctx.stroke()}rows.forEach((x,i)=>{let xx=pad+i*w+w/2, up=x.c>=x.o;ctx.strokeStyle=up?'#a9d39a':'#e48b8b';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(xx,y(x.h));ctx.lineTo(xx,y(x.l));ctx.stroke();let yo=y(x.o),yc=y(x.c);ctx.fillRect(xx-w*.28,Math.min(yo,yc),w*.56,Math.max(2,Math.abs(yc-yo)))});let last=rows.at(-1), highs=rows.slice(-20).map(x=>x.h), lows=rows.slice(-20).map(x=>x.l), swingH=Math.max(...highs),swingL=Math.min(...lows);ctx.fillStyle='#c6ddb9';ctx.font='16px sans-serif';ctx.fillText(`Last ${fmt(last.c,last.c<100?4:0)}   20H ${fmt(swingH,0)}   20L ${fmt(swingL,0)}`,pad,20)}

function renderPlanner(){let opts=state.symbols.map(s=>`<option value="${s.venue}|${s.symbol}">${s.venue} · ${s.label}</option>`).join('');$('#view').innerHTML=`<div class="section-title"><h2>Trade Planner</h2></div><div class="card"><div class="form-grid"><div class="field full"><label>Market</label><select id="pMarket">${opts}</select></div><div class="field"><label>Entry</label><input id="pEntry" type="number" step="any"></div><div class="field"><label>Stop / Invalidation</label><input id="pStop" type="number" step="any"></div><div class="field"><label>Target 1</label><input id="pTp1" type="number" step="any"></div><div class="field"><label>Target 2</label><input id="pTp2" type="number" step="any"></div><div class="field"><label>Risk %</label><input id="pRisk" type="number" step="0.1" value="${state.settings.riskPct}"></div><div class="field"><label>Signal Grade</label><select id="pGrade"><option>A</option><option>B</option><option>C</option></select></div><div class="field full"><label>Setup</label><select id="pSetup"><option>Liquidity Sweep + CHoCH</option><option>BOS + Retest</option><option>Demand / Supply Reaction</option><option>Breakout + Retest</option><option>Manual</option></select></div></div><div class="hr"></div><button class="btn block" onclick="calcPlan()">Calculate Position</button><div id="planOut"></div></div>`}
function prefillPlanner(v,s){closeModal();tab='planner';render();$('#pMarket').value=`${v}|${s}`;let p=prices[s]?.price||0;if(p)$('#pEntry').value=p}
function calcPlan(){let entry=+$(`#pEntry`).value,stop=+$(`#pStop`).value,tp1=+$(`#pTp1`).value,tp2=+$(`#pTp2`).value,risk=+$(`#pRisk`).value||1;if(!entry||!stop||entry===stop){toast('Enter a valid entry and stop');return}let riskCash=state.settings.capital*risk/100,unitRisk=Math.abs(entry-stop),qty=riskCash/unitRisk,rr1=tp1?Math.abs(tp1-entry)/unitRisk:0,rr2=tp2?Math.abs(tp2-entry)/unitRisk:0;$('#planOut').innerHTML=`<div class="hr"></div><div class="signal-box"><div class="label">Suggested Position Size</div><div class="metric">${fmt(qty,6)}</div><table class="mini-table"><tr><td>Risk amount</td><td>${fmt(riskCash,0)}</td></tr><tr><td>R:R to TP1</td><td>${fmt(rr1,2)}</td></tr><tr><td>R:R to TP2</td><td>${fmt(rr2,2)}</td></tr></table><button class="btn block" style="margin-top:10px" onclick="savePlannedTrade(${qty})">Save to Journal</button></div>`}
function savePlannedTrade(qty){let [venue,symbol]=$('#pMarket').value.split('|');state.journal.unshift({id:crypto.randomUUID(),created:now(),venue,symbol,side:'LONG',status:'PLANNED',grade:$('#pGrade').value,setup:$('#pSetup').value,entry:+$('#pEntry').value,stop:+$('#pStop').value,tp1:+$('#pTp1').value,tp2:+$('#pTp2').value,plannedQty:qty,notes:'',fills:[]});save();toast('Trade plan saved')}

function renderJournal(){let cards=state.journal.map(t=>{let r=realizedPL(t),pl=r.pl;return `<div class="card journal-card"><div class="journal-head"><div><div class="symbol">${t.symbol} <span class="pill">${t.venue}</span></div><div class="venue">${new Date(t.created).toLocaleString()} · ${t.status} · Grade ${t.grade||'-'}</div></div><div class="price ${pl>=0?'pos':'neg'}">${fmt(pl,0)}<div class="venue">Realized P/L</div></div></div><div class="hr"></div><table class="mini-table"><tr><td>Plan Entry</td><td>${fmt(t.entry,4)}</td></tr><tr><td>Stop</td><td>${fmt(t.stop,4)}</td></tr><tr><td>TP1 / TP2</td><td>${fmt(t.tp1,4)} / ${fmt(t.tp2,4)}</td></tr><tr><td>Open Qty</td><td>${fmt(r.open,6)}</td></tr></table><div class="journal-actions"><button class="btn secondary" onclick="editTrade('${t.id}')">Edit</button><button class="btn" onclick="fillsModal('${t.id}')">Fills</button></div></div>`}).join('');$('#view').innerHTML=`<div class="section-title"><h2>Trade Journal</h2><button onclick="newTradeModal()">+ Trade</button></div>${cards||'<div class="card"><div class="subtle">No trades yet.</div></div>'}`}
function newTradeModal(){modal(`<h2>New Trade</h2>${tradeForm({venue:'Nobitex',symbol:'USDTIRT',side:'LONG',status:'PLANNED',grade:'B',entry:0,stop:0,tp1:0,tp2:0,setup:'Manual',notes:''})}<button class="btn block" onclick="createTrade()">Create</button>`)}
function tradeForm(t){return `<div class="form-grid"><div class="field"><label>Venue</label><select id="eVenue"><option ${t.venue==='Toobit'?'selected':''}>Toobit</option><option ${t.venue==='Nobitex'?'selected':''}>Nobitex</option><option ${t.venue==='Digikala Gold'?'selected':''}>Digikala Gold</option></select></div><div class="field"><label>Symbol</label><input id="eSymbol" value="${t.symbol||''}"></div><div class="field"><label>Status</label><select id="eStatus">${['PLANNED','OPEN','PARTIAL','CLOSED','CANCELLED'].map(x=>`<option ${t.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Grade</label><select id="eGrade">${['A','B','C'].map(x=>`<option ${t.grade===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Plan Entry</label><input id="eEntry" type="number" step="any" value="${t.entry||0}"></div><div class="field"><label>Stop</label><input id="eStop" type="number" step="any" value="${t.stop||0}"></div><div class="field"><label>TP1</label><input id="eTp1" type="number" step="any" value="${t.tp1||0}"></div><div class="field"><label>TP2</label><input id="eTp2" type="number" step="any" value="${t.tp2||0}"></div><div class="field full"><label>Setup</label><input id="eSetup" value="${t.setup||''}"></div><div class="field full"><label>Notes</label><textarea id="eNotes">${t.notes||''}</textarea></div></div><div class="hr"></div>`}
function createTrade(){state.journal.unshift({id:crypto.randomUUID(),created:now(),venue:$('#eVenue').value,symbol:$('#eSymbol').value.toUpperCase(),side:'LONG',status:$('#eStatus').value,grade:$('#eGrade').value,entry:+$('#eEntry').value,stop:+$('#eStop').value,tp1:+$('#eTp1').value,tp2:+$('#eTp2').value,setup:$('#eSetup').value,notes:$('#eNotes').value,fills:[]});save();closeModal();render()}
function editTrade(id){let t=state.journal.find(x=>x.id===id);modal(`<h2>Edit Trade</h2>${tradeForm(t)}<div class="row"><button class="btn danger" onclick="deleteTrade('${id}')">Delete</button><button class="btn" style="flex:1" onclick="updateTrade('${id}')">Save Changes</button></div>`)}
function updateTrade(id){let t=state.journal.find(x=>x.id===id);Object.assign(t,{venue:$('#eVenue').value,symbol:$('#eSymbol').value.toUpperCase(),status:$('#eStatus').value,grade:$('#eGrade').value,entry:+$('#eEntry').value,stop:+$('#eStop').value,tp1:+$('#eTp1').value,tp2:+$('#eTp2').value,setup:$('#eSetup').value,notes:$('#eNotes').value});save();closeModal();render()}
function deleteTrade(id){state.journal=state.journal.filter(x=>x.id!==id);save();closeModal();render()}
function fillsModal(id){let t=state.journal.find(x=>x.id===id);let rows=(t.fills||[]).map((f,i)=>`<div class="market-row"><div><strong>${f.type}</strong><div class="venue">${new Date(f.time).toLocaleString()}</div></div><div class="price">${fmt(f.qty,6)} @ ${fmt(f.price,4)}<div><button class="btn secondary" onclick="editFill('${id}',${i})">Edit</button></div></div></div>`).join('');modal(`<h2>Trade Fills · ${t.symbol}</h2>${rows||'<div class="subtle">No fills yet.</div>'}<div class="hr"></div><button class="btn block" onclick="addFillModal('${id}')">+ Add Fill</button>`)}
function addFillModal(id,i=null){let t=state.journal.find(x=>x.id===id),f=i===null?{type:'BUY',qty:0,price:0,fee:0,time:now()}:(t.fills[i]);modal(`<h2>${i===null?'Add':'Edit'} Fill</h2><div class="form-grid"><div class="field"><label>Type</label><select id="fType"><option ${f.type==='BUY'?'selected':''}>BUY</option><option ${f.type==='SELL'?'selected':''}>SELL</option></select></div><div class="field"><label>Quantity</label><input id="fQty" type="number" step="any" value="${f.qty}"></div><div class="field"><label>Price</label><input id="fPrice" type="number" step="any" value="${f.price}"></div><div class="field"><label>Fee</label><input id="fFee" type="number" step="any" value="${f.fee||0}"></div></div><div class="hr"></div><button class="btn block" onclick="saveFill('${id}',${i===null?'null':i})">Save Fill</button>${i!==null?`<button class="btn danger block" style="margin-top:8px" onclick="deleteFill('${id}',${i})">Delete Fill</button>`:''}`)}
function editFill(id,i){addFillModal(id,i)}
function saveFill(id,i){let t=state.journal.find(x=>x.id===id),f={type:$('#fType').value,qty:+$('#fQty').value,price:+$('#fPrice').value,fee:+$('#fFee').value,time:now()};t.fills=t.fills||[];if(i===null)t.fills.push(f);else t.fills[i]={...t.fills[i],...f};let r=realizedPL(t);t.status=r.open>0?(r.sq>0?'PARTIAL':'OPEN'):(r.bq>0?'CLOSED':t.status);save();fillsModal(id)}
function deleteFill(id,i){let t=state.journal.find(x=>x.id===id);t.fills.splice(i,1);save();fillsModal(id)}

function renderSettings(){$('#view').innerHTML=`<div class="section-title"><h2>Settings</h2></div><div class="card"><div class="form-grid"><div class="field full"><label>Trading Capital (Toman)</label><input id="sCap" type="number" value="${state.settings.capital}"></div><div class="field"><label>Default Risk %</label><input id="sRisk" type="number" step="0.1" value="${state.settings.riskPct}"></div><div class="field"><label>Digikala Gold Price</label><input id="sGold" type="number" step="any" value="${state.settings.dgGoldPrice}"></div></div><div class="hr"></div><button class="btn block" onclick="saveSettings()">Save Settings</button></div><div class="section-title"><h2>Data</h2></div><div class="card"><div class="row wrap"><button class="btn secondary" onclick="exportData()">Export Backup</button><button class="btn secondary" onclick="importData()">Import Backup</button></div><div class="hr"></div><div class="subtle">Private API keys are intentionally not stored in this browser version. Use the desktop edition for read-only account connections, or add a secure backend / native Keychain layer later.</div></div><div class="section-title"><h2>Install on iPhone</h2></div><div class="card"><div class="subtle">Open the hosted app in Safari → Share → Add to Home Screen. The app then launches full-screen like a native app.</div></div>`}
function saveSettings(){state.settings.capital=+$(`#sCap`).value;state.settings.riskPct=+$(`#sRisk`).value;state.settings.dgGoldPrice=+$(`#sGold`).value;save();render();toast('Settings saved')}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='TAJDARA_MM_backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{try{state=JSON.parse(await i.files[0].text());save();render();toast('Backup imported')}catch{toast('Invalid backup')}};i.click()}

$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;render()}));
$('#refreshAll').addEventListener('click',refreshPrices);
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
render();refreshPrices();
setInterval(refreshPrices,60000);
